version: '3'

services:
  listmonk:
    image: listmonk/listmonk:latest
    command: sh -c "yes | ./listmonk --install --idempotent && ./listmonk"
    environment:
      LISTMONK_db__host: ${DB_HOST}
      LISTMONK_db__port: ${DB_PORT:-5432}
      LISTMONK_db__user: ${DB_USER}
      LISTMONK_db__password: ${DB_PASSWORD}
      LISTMONK_db__database: ${DB_NAME}
      LISTMONK_app__address: 0.0.0.0:9000
      TZ: ${TIMEZONE:-UTC}
    restart: always
    ports:
      - "9000:9000"
